language: cpp
dist: focal

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y meson ninja-build libgtk-4-dev libpoppler-glib-dev libcups2-dev gettext

script:
  - meson setup builddir
  - cd builddir
  - ninja
  - ninja test

notifications:
  email: false
